######################################################################
#
# File name : top_tb_simulate.do
# Created on: Thu Jun 06 15:42:15 +0800 2024
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L secureip -lib xil_defaultlib xil_defaultlib.top_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {top_tb_wave.do}

view wave
view structure
view signals

log -r /*

do {top_tb.udo}

run 200us
