######################################################################
#
# File name : top_tb_compile.do
# Created on: Thu Jun 06 15:42:12 +0800 2024
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
F:\\FPGA\\Modelsim2020\\win64\\vlib modelsim_lib/work
F:\\FPGA\\Modelsim2020\\win64\\vlib modelsim_lib/msim

F:\\FPGA\\Modelsim2020\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\FPGA\\Modelsim2020\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\FPGA\\Modelsim2020\\win64\\vlog  -incr -mfcu -work xil_defaultlib  \
"top_tb_func_impl.v" \
"../../../../../FPGA_BU01.srcs/sim_1/new/top_tb.v" \


quit -force

