######################################################################
#
# File name : top_tb_wave.do
# Created on: Wed Jun 05 21:39:58 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
