######################################################################
#
# File name : top_tb_wave.do
# Created on: Sat Jun 08 22:03:02 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
