// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\FPGA_myself\DVB-S\HDL_Gen\RRCFilter\Raised_Cosine_Transmit_Filter.v
// Created: 2024-05-25 14:15:28
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Raised_Cosine_Transmit_Filter
// Source Path: RRCFilter/RRC Filter/Raised Cosine Transmit Filter
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Raised_Cosine_Transmit_Filter
          (clk,
           reset,
           enb_1_1_1,
           In1,
           Out1);


  input   clk;
  input   reset;
  input   enb_1_1_1;
  input   signed [7:0] In1;  // int8
  output  signed [31:0] Out1;  // sfix32_En30


  wire signed [31:0] FIR_Interpolation_out1;  // sfix32_En30


  FIR_Interpolation u_FIR_Interpolation (.clk(clk),
                                         .enb_1_1_1(enb_1_1_1),
                                         .reset(reset),
                                         .FIR_Interpolation_in(In1),  // int8
                                         .FIR_Interpolation_out(FIR_Interpolation_out1)  // sfix32_En30
                                         );

  assign Out1 = FIR_Interpolation_out1;

endmodule  // Raised_Cosine_Transmit_Filter

