webtalk_init -webtalk_dir D:/desktop/FPGA/DVB/DVBS/hdl_prj/hdlsrc/dbvs/dbvs.sim/sim_1/behav/xsim/xsim.dir/rs_en_test_wrapper_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 16 18:33:28 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "aba301aa-9bf9-4965-926a-66801a1c7785" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d6bd0652c506452fac9124e4bf05d4a4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2688 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "10168_KB" -context "xsim\\usage"
webtalk_transmit -clientid 432910622 -regid "" -xml D:/desktop/FPGA/DVB/DVBS/hdl_prj/hdlsrc/dbvs/dbvs.sim/sim_1/behav/xsim/xsim.dir/rs_en_test_wrapper_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/desktop/FPGA/DVB/DVBS/hdl_prj/hdlsrc/dbvs/dbvs.sim/sim_1/behav/xsim/xsim.dir/rs_en_test_wrapper_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/desktop/FPGA/DVB/DVBS/hdl_prj/hdlsrc/dbvs/dbvs.sim/sim_1/behav/xsim/xsim.dir/rs_en_test_wrapper_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
