# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/topConstrain.xdc

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_util_ds_buf_0_0/top_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_util_ds_buf_0_0 || ORIG_REF_NAME==top_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/top/ip/top_Con_Encoder_0_0/top_Con_Encoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_Con_Encoder_0_0 || ORIG_REF_NAME==top_Con_Encoder_0_0} -quiet] -quiet

# IP: bd/top/ip/top_dds_compiler_0_0/top_dds_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dds_compiler_0_0 || ORIG_REF_NAME==top_dds_compiler_0_0} -quiet] -quiet

# IP: bd/top/ip/top_fir_compiler_0_0/top_fir_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_fir_compiler_0_0 || ORIG_REF_NAME==top_fir_compiler_0_0} -quiet] -quiet

# IP: bd/top/ip/top_PolarityShift_0_0/top_PolarityShift_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_PolarityShift_0_0 || ORIG_REF_NAME==top_PolarityShift_0_0} -quiet] -quiet

# IP: bd/top/ip/top_PolarityShift_1_0/top_PolarityShift_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_PolarityShift_1_0 || ORIG_REF_NAME==top_PolarityShift_1_0} -quiet] -quiet

# IP: bd/top/ip/top_fir_compiler_0_2/top_fir_compiler_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_fir_compiler_0_2 || ORIG_REF_NAME==top_fir_compiler_0_2} -quiet] -quiet

# IP: bd/top/ip/top_dds_compiler_0_1/top_dds_compiler_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dds_compiler_0_1 || ORIG_REF_NAME==top_dds_compiler_0_1} -quiet] -quiet

# IP: bd/top/ip/top_mult_gen_0_0/top_mult_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_mult_gen_0_0 || ORIG_REF_NAME==top_mult_gen_0_0} -quiet] -quiet

# IP: bd/top/ip/top_mult_gen_0_1/top_mult_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_mult_gen_0_1 || ORIG_REF_NAME==top_mult_gen_0_1} -quiet] -quiet

# IP: bd/top/ip/top_c_addsub_0_0/top_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_c_addsub_0_0 || ORIG_REF_NAME==top_c_addsub_0_0} -quiet] -quiet

# IP: bd/top/ip/top_terminal_0_0/top_terminal_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_terminal_0_0 || ORIG_REF_NAME==top_terminal_0_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconstant_0_0/top_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconstant_0_0 || ORIG_REF_NAME==top_xlconstant_0_0} -quiet] -quiet

# IP: bd/top/ip/top_RS_Enc_0_0/top_RS_Enc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_RS_Enc_0_0 || ORIG_REF_NAME==top_RS_Enc_0_0} -quiet] -quiet

# IP: bd/top/ip/top_DataSource_Scrambler_0_1/top_DataSource_Scrambler_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_DataSource_Scrambler_0_1 || ORIG_REF_NAME==top_DataSource_Scrambler_0_1} -quiet] -quiet

# IP: bd/top/ip/top_dec2bin_0_3/top_dec2bin_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dec2bin_0_3 || ORIG_REF_NAME==top_dec2bin_0_3} -quiet] -quiet

# IP: bd/top/ip/top_Interleaver_0_0/top_Interleaver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_Interleaver_0_0 || ORIG_REF_NAME==top_Interleaver_0_0} -quiet] -quiet

# XDC: f:/Git_Repository/DVB-S/FPGA_BU01/FPGA_BU01.gen/sources_1/bd/top/top_ooc.xdc
