# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Git_Repository/FPGA_myself/DVB-S/vivado/vivado.srcs/sources_1/bd/top/ip/top_ila_0_0/top_ila_0_0.xci
# IP: The module: 'top_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Git_Repository/FPGA_myself/DVB-S/vivado/vivado.gen/sources_1/bd/top/ip/top_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/Git_Repository/FPGA_myself/DVB-S/vivado/vivado.gen/sources_1/bd/top/ip/top_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/Git_Repository/FPGA_myself/DVB-S/vivado/vivado.gen/sources_1/bd/top/ip/top_ila_0_0/top_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: F:/Git_Repository/FPGA_myself/DVB-S/vivado/vivado.srcs/sources_1/bd/top/ip/top_ila_0_0/top_ila_0_0.xci
# IP: The module: 'top_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Git_Repository/FPGA_myself/DVB-S/vivado/vivado.gen/sources_1/bd/top/ip/top_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/Git_Repository/FPGA_myself/DVB-S/vivado/vivado.gen/sources_1/bd/top/ip/top_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/Git_Repository/FPGA_myself/DVB-S/vivado/vivado.gen/sources_1/bd/top/ip/top_ila_0_0/top_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
