// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\DVBS\Counter_Limited.v
// Created: 2024-04-15 20:42:57
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Counter_Limited
// Source Path: DVBS/dec2bin2/Counter Limited
// Hierarchy Level: 1
// Model version: 1.32
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Counter_Limited
          (clk,
           reset,
           enb_1_8_0,
           y);


  input   clk;
  input   reset;
  input   enb_1_8_0;
  output  [7:0] y;  // uint8


  reg [7:0] Output_out1;  // uint8
  wire [7:0] Increment_Real_World_out1;  // uint8
  wire [7:0] Wrap_To_Zero_out1;  // uint8


  Increment_Real_World u_Increment_Real_World (.u(Output_out1),  // uint8
                                               .y(Increment_Real_World_out1)  // uint8
                                               );

  Wrap_To_Zero u_Wrap_To_Zero (.U(Increment_Real_World_out1),  // uint8
                               .Y(Wrap_To_Zero_out1)  // uint8
                               );

  always @(posedge clk or posedge reset)
    begin : Output_rsvd_process
      if (reset == 1'b1) begin
        Output_out1 <= 8'b00000000;
      end
      else begin
        if (enb_1_8_0) begin
          Output_out1 <= Wrap_To_Zero_out1;
        end
      end
    end



  assign y = Output_out1;

endmodule  // Counter_Limited

