// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\DVB-S\HDL_Gen\SuFrame_Scrambler\DataSource_Scrambler.v
// Created: 2024-05-31 10:26:21
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 5e-09
// Target subsystem base rate: 5e-09
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        5e-09
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// simStart                      ce_out        5e-09
// simEnd                        ce_out        5e-09
// simEN                         ce_out        5e-09
// ScramblerOut                  ce_out        5e-09
// BinEn                         ce_out        5e-09
// DataGenEn                     ce_out        5e-09
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DataSource_Scrambler
// Source Path: SuFrame_Scrambler/DataSource_Scrambler
// Hierarchy Level: 0
// Model version: 1.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DataSource_Scrambler
          (clk,
           rst_n,
           clk_enable,
           ce_out,
           simStart,
           simEnd,
           simEN,
           ScramblerOut,
           BinEn,
           DataGenEn);


  input   clk;
  input   rst_n;
  input   clk_enable;
  output  ce_out;
  output  simStart;
  output  simEnd;
  output  simEN;
  output  [7:0] ScramblerOut;  // uint8
  output  BinEn;
  output  DataGenEn;


  wire CLKdivide_out1;
  wire CLKdivide_out2;
  wire [7:0] sigSource_out4;  // uint8
  wire HeaderProcess_out1;
  wire HeaderProcess_out2;
  wire HeaderProcess_out3;
  wire [7:0] HeaderProcess_out4;  // uint8
  wire sigSource_out1;
  wire sigSource_out2;
  wire sigSource_out3;
  wire [7:0] myScrambler_out1;  // uint8


  CLKdivide u_CLKdivide (.clk(clk),
                         .rst_n(rst_n),
                         .enb(clk_enable),
                         .DataGenEn(CLKdivide_out1),
                         .BinEn(CLKdivide_out2)
                         );

  HeaderProcess u_HeaderProcess (.clk(clk),
                                 .rst_n(rst_n),
                                 .enb(clk_enable),
                                 .simDataIn(sigSource_out4),  // uint8
                                 .DataGenEn(CLKdivide_out1),
                                 .DataGenEN_1(HeaderProcess_out1),
                                 .ScrambleEn(HeaderProcess_out2),
                                 .ScrambleRst(HeaderProcess_out3),
                                 .DataIn(HeaderProcess_out4)  // uint8
                                 );

  sigSource u_sigSource (.clk(clk),
                         .rst_n(rst_n),
                         .enb(clk_enable),
                         .DataGenEn(CLKdivide_out1),
                         .Enable(HeaderProcess_out1),
                         .simStart(sigSource_out1),
                         .simEnd(sigSource_out2),
                         .simEN(sigSource_out3),
                         .simDataIn(sigSource_out4)  // uint8
                         );

  assign simStart = sigSource_out1;

  assign simEnd = sigSource_out2;

  assign simEN = sigSource_out3;

  myScrambler u_myScrambler (.clk(clk),
                             .rst_n(rst_n),
                             .enb(clk_enable),
                             .DataIn(HeaderProcess_out4),  // uint8
                             .EN(HeaderProcess_out2),
                             .RST_IniState(HeaderProcess_out3),
                             .Trigger(CLKdivide_out1),
                             .Out1(myScrambler_out1)  // uint8
                             );

  assign ScramblerOut = myScrambler_out1;

  assign BinEn = CLKdivide_out2;

  assign DataGenEn = CLKdivide_out1;

  assign ce_out = clk_enable;

endmodule  // DataSource_Scrambler

