# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Git_Repository/DVB-S/FPGA_BU01/FPGA_BU01.srcs/sources_1/bd/top/ip/top_fir_compiler_0_2/top_fir_compiler_0_2.xci
# IP: The module: 'top_fir_compiler_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Git_Repository/DVB-S/FPGA_BU01/FPGA_BU01.gen/sources_1/bd/top/ip/top_fir_compiler_0_2/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_fir_compiler_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Git_Repository/DVB-S/FPGA_BU01/FPGA_BU01.gen/sources_1/bd/top/ip/top_fir_compiler_0_2/top_fir_compiler_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_fir_compiler_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: F:/Git_Repository/DVB-S/FPGA_BU01/FPGA_BU01.srcs/sources_1/bd/top/ip/top_fir_compiler_0_2/top_fir_compiler_0_2.xci
# IP: The module: 'top_fir_compiler_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Git_Repository/DVB-S/FPGA_BU01/FPGA_BU01.gen/sources_1/bd/top/ip/top_fir_compiler_0_2/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_fir_compiler_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Git_Repository/DVB-S/FPGA_BU01/FPGA_BU01.gen/sources_1/bd/top/ip/top_fir_compiler_0_2/top_fir_compiler_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_fir_compiler_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
