######################################################################
#
# File name : top_tb_wave.do
# Created on: Thu Jun 06 13:31:25 +0800 2024
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
