######################################################################
#
# File name : top_tb_simulate.do
# Created on: Thu Jun 06 14:15:57 +0800 2024
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vsim -voptargs="+acc" +transport_int_delays +pulse_e/0 +pulse_int_e/0 +pulse_r/0 +pulse_int_r/0 -L xil_defaultlib -L simprims_ver -L secureip -lib xil_defaultlib xil_defaultlib.top_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {top_tb_wave.do}

view wave
view structure
view signals

do {top_tb.udo}

run 200us
