// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\DVB-S\HDL_Gen\DVBS\bit_sys.v
// Created: 2024-06-09 10:16:42
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: bit_sys
// Source Path: DVBS/DataSource_Scrambler/bit_sys
// Hierarchy Level: 1
// Model version: 1.64
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module bit_sys
          (clk,
           reset_n,
           enb,
           simStart,
           simEnd,
           simEN,
           Enable,
           Out1,
           Out2,
           Out3);


  input   clk;
  input   reset_n;
  input   enb;
  input   simStart;
  input   simEnd;
  input   simEN;
  input   Enable;
  output  Out1;
  output  Out2;
  output  Out3;


  wire enb_gated;
  reg  Delay_out1_hold;
  reg  Delay1_out1_hold;
  reg  Delay2_out1_hold;


  assign enb_gated = Enable && enb;

  always @(posedge clk or negedge reset_n)
    begin : Out1_hold_process
      if (reset_n == 1'b0) begin
        Delay_out1_hold <= 1'b0;
      end
      else begin
        if (enb_gated) begin
          Delay_out1_hold <= simStart;
        end
      end
    end



  assign Out1 = Delay_out1_hold;

  always @(posedge clk or negedge reset_n)
    begin : Out2_hold_process
      if (reset_n == 1'b0) begin
        Delay1_out1_hold <= 1'b0;
      end
      else begin
        if (enb_gated) begin
          Delay1_out1_hold <= simEnd;
        end
      end
    end



  assign Out2 = Delay1_out1_hold;

  always @(posedge clk or negedge reset_n)
    begin : Out3_hold_process
      if (reset_n == 1'b0) begin
        Delay2_out1_hold <= 1'b0;
      end
      else begin
        if (enb_gated) begin
          Delay2_out1_hold <= simEN;
        end
      end
    end



  assign Out3 = Delay2_out1_hold;

endmodule  // bit_sys

