// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\FPGA_myself\DVB-S\HDL_Gen\DVBS\Con_Encoder.v
// Created: 2024-05-16 18:07:42
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1.5625e-06
// Target subsystem base rate: 1.25e-05
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1.25e-05
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ConvOut_0                     ce_out        1.25e-05
// ConvOut_1                     ce_out        1.25e-05
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Con_Encoder
// Source Path: DVBS/Con_Encoder
// Hierarchy Level: 0
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Con_Encoder
          (clk,
           reset_n,
           clk_enable,
           In1,
           ce_out,
           ConvOut_0,
           ConvOut_1);


  input   clk;
  input   reset_n;
  input   clk_enable;
  input   In1;
  output  ce_out;
  output  ConvOut_0;  // boolean
  output  ConvOut_1;  // boolean


  wire Constant2_out1;
  wire Convolutional_Encoder2_out1_0;
  wire Convolutional_Encoder2_out1_1;


  assign Constant2_out1 = 1'b1;



  Convolutional_Encoder2 u_Convolutional_Encoder2 (.clk(clk),
                                                   .reset_n(reset_n),
                                                   .enb_1_8_0(clk_enable),
                                                   .in0(In1),
                                                   .in1(Constant2_out1),
                                                   .out0_0(Convolutional_Encoder2_out1_0),  // boolean
                                                   .out0_1(Convolutional_Encoder2_out1_1)  // boolean
                                                   );

  assign ConvOut_0 = Convolutional_Encoder2_out1_0;

  assign ConvOut_1 = Convolutional_Encoder2_out1_1;

  assign ce_out = clk_enable;

endmodule  // Con_Encoder

