// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\FPGA_myself\DVB-S\HDL_Gen\DVBS\Con_Interleaver.v
// Created: 2024-05-15 20:38:07
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1.5625e-06
// Target subsystem base rate: 0.0001
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.0001
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1                          ce_out        0.0001
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Con_Interleaver
// Source Path: DVBS/Con_Interleaver
// Hierarchy Level: 0
// Model version: 1.48
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Con_Interleaver
          (clk,
           reset_n,
           clk_enable,
           In1,
           ce_out,
           Out1);


  input   clk;
  input   reset_n;
  input   clk_enable;
  input   [7:0] In1;  // uint8
  output  ce_out;
  output  [7:0] Out1;  // uint8


  wire [7:0] Convolutional_Interleaver_out1;  // uint8


  Convolutional_Interleaver u_Convolutional_Interleaver (.clk(clk),
                                                         .reset_n(reset_n),
                                                         .enb_1_64_0(clk_enable),
                                                         .In1(In1),  // uint8
                                                         .Convolutional_Interleaver_out1(Convolutional_Interleaver_out1)  // uint8
                                                         );

  assign Out1 = Convolutional_Interleaver_out1;

  assign ce_out = clk_enable;

endmodule  // Con_Interleaver

