// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\DVB-S\HDL_Gen\DVBS\Con_Encoder.v
// Created: 2024-06-06 15:06:20
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 5e-09
// Target subsystem base rate: 5e-09
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        5e-09
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ConvOut_0                     ce_out        5e-09
// ConvOut_1                     ce_out        5e-09
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Con_Encoder
// Source Path: DVBS/Con_Encoder
// Hierarchy Level: 0
// Model version: 1.63
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ps

module Con_Encoder
          (clk,
           reset_n,
           clk_enable,
           In1,
           VldIn,
           ce_out,
           ConvOut_0,
           ConvOut_1);


  input   clk;
  input   reset_n;
  input   clk_enable;
  input   In1;
  input   VldIn;
  output  ce_out;
  output  ConvOut_0;  // boolean
  output  ConvOut_1;  // boolean


  wire Convolutional_Encoder2_out1_0;
  wire Convolutional_Encoder2_out1_1;


  Convolutional_Encoder2 u_Convolutional_Encoder2 (.clk(clk),
                                                   .reset_n(reset_n),
                                                   .enb(clk_enable),
                                                   .in0(In1),
                                                   .in1(VldIn),
                                                   .out0_0(Convolutional_Encoder2_out1_0),  // boolean
                                                   .out0_1(Convolutional_Encoder2_out1_1)  // boolean
                                                   );

  assign ConvOut_0 = Convolutional_Encoder2_out1_0;

  assign ConvOut_1 = Convolutional_Encoder2_out1_1;

  assign ce_out = clk_enable;

endmodule  // Con_Encoder

