// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\FPGA_myself\DVB-S\HDL_Gen\DVBS\dec2bin_tc.v
// Created: 2024-05-15 21:10:25
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dec2bin_tc
// Source Path: dec2bin_tc
// Hierarchy Level: 1
// 
// Master clock enable input: clk_enable
// 
// enb_1_8_0   : identical to clk_enable
// enb_1_8_1   : identical to clk_enable
// enb_1_64_0  : 8x slower than clk with last phase
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dec2bin_tc
          (clk,
           reset_n,
           clk_enable,
           enb_1_8_0,
           enb_1_8_1,
           enb_1_64_0);


  input   clk;
  input   reset_n;
  input   clk_enable;
  output  enb_1_8_0;
  output  enb_1_8_1;
  output  enb_1_64_0;


  reg [2:0] count8;  // ufix3
  wire comp_0_tmp;
  wire phase_0_tmp;
  reg  phase_0;
  wire enb_1_64_0_1;


  assign enb_1_8_0 = clk_enable;

  assign enb_1_8_1 = clk_enable;

  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 7
  always @(posedge clk or negedge reset_n)
    begin : counter_8_process
      if (reset_n == 1'b0) begin
        count8 <= 3'b001;
      end
      else begin
        if (clk_enable) begin
          count8 <= count8 + 3'b001;
        end
      end
    end



  assign comp_0_tmp = count8 == 3'b111;



  assign phase_0_tmp = comp_0_tmp & clk_enable;



  always @(posedge clk or negedge reset_n)
    begin : phase_delay_process
      if (reset_n == 1'b0) begin
        phase_0 <= 1'b0;
      end
      else begin
        if (clk_enable) begin
          phase_0 <= phase_0_tmp;
        end
      end
    end



  assign enb_1_64_0_1 = phase_0 & clk_enable;



  assign enb_1_64_0 = enb_1_64_0_1;

endmodule  // dec2bin_tc

