// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\DVB-S\HDL_Gen\DVBS\Detect_Rise_Positive_block.v
// Created: 2024-06-06 20:21:53
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Detect_Rise_Positive_block
// Source Path: DVBS/DataSource_Scrambler/Detect Rise Positive
// Hierarchy Level: 1
// Model version: 1.63
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ps

module Detect_Rise_Positive_block
          (clk,
           reset_n,
           enb,
           U,
           Y);


  input   clk;
  input   reset_n;
  input   enb;
  input   U;
  output  Y;


  wire U_k;
  reg  U_k_1;
  wire FixPt_Relational_Operator_relop1;

  // U(k)
  // Edge


  Positive_block u_Positive (.u(U),
                             .y(U_k)
                             );

  // 
  // Store in Global RAM
  always @(posedge clk or negedge reset_n)
    begin : Delay_Input1_process
      if (reset_n == 1'b0) begin
        U_k_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          U_k_1 <= U_k;
        end
      end
    end



  assign FixPt_Relational_Operator_relop1 = U_k > U_k_1;



  assign Y = FixPt_Relational_Operator_relop1;

endmodule  // Detect_Rise_Positive_block

