open_system('DVBS');
open_system('gm_DVBS');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DVBS/sigSource/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_DVBS/sigSource/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('DVBS/sigSource/1-D Lookup Table', 'user1');
annotate_port('DVBS/sigSource/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
