open_system('DVBS');
open_system('gm_DVBS');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DVBS/DataSource_Scrambler/HeaderProcess/Multiport Switch', 'user1');
annotate_port('gm_DVBS/DataSource_Scrambler/HeaderProcess/Multiport Switch', 0, 1, 'Blocks delay absorption: 1 cycles');
hilite_system('DVBS/DataSource_Scrambler/HeaderProcess/Multiport Switch', 'user1');
annotate_port('DVBS/DataSource_Scrambler/HeaderProcess/Multiport Switch', 0, 1, 'Blocks delay absorption: 1 cycles');
