// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\DVB-S\HDL_Gen\DVBS\Positive_block1.v
// Created: 2024-06-06 20:21:53
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Positive_block1
// Source Path: DVBS/DataSource_Scrambler/Detect Rise Positive1/Positive
// Hierarchy Level: 2
// Model version: 1.63
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ps

module Positive_block1
          (u,
           y);


  input   u;
  output  y;


  wire Constant_out1;
  wire Compare_relop1;


  assign Constant_out1 = 1'b0;



  assign Compare_relop1 = u > Constant_out1;



  assign y = Compare_relop1;

endmodule  // Positive_block1

