// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\FPGA_myself\DVB-S\HDL_Gen\DVBS\RS.v
// Created: 2024-05-15 20:44:20
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1.5625e-06
// Target subsystem base rate: 0.0001
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.0001
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// RS_Out                        ce_out        0.0001
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RS
// Source Path: DVBS/RS
// Hierarchy Level: 0
// Model version: 1.48
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RS
          (clk,
           reset_n,
           clk_enable,
           RS_In,
           RS_Start,
           RS_End,
           RS_VLD,
           ce_out,
           RS_Out);


  input   clk;
  input   reset_n;
  input   clk_enable;
  input   [7:0] RS_In;  // uint8
  input   RS_Start;
  input   RS_End;
  input   RS_VLD;
  output  ce_out;
  output  [7:0] RS_Out;  // uint8


  wire [7:0] Integer_Input_RS_Encoder_HDL_Optimized_out1;  // uint8


  Integer_Input_RS_Encoder_HDL_Optimized u_Integer_Input_RS_Encoder_HDL_Optimized (.clk(clk),
                                                                                   .reset_n(reset_n),
                                                                                   .enb_1_64_0(clk_enable),
                                                                                   .Integer_Input_RS_Encoder_HDL_Optimized_in(RS_In),  // uint8
                                                                                   .Integer_Input_RS_Encoder_HDL_Optimized_start(RS_Start),
                                                                                   .Integer_Input_RS_Encoder_HDL_Optimized_end(RS_End),
                                                                                   .Integer_Input_RS_Encoder_HDL_Optimized_datavalid(RS_VLD),
                                                                                   .Integer_Input_RS_Encoder_HDL_Optimized_out(Integer_Input_RS_Encoder_HDL_Optimized_out1)  // uint8
                                                                                   );

  assign RS_Out = Integer_Input_RS_Encoder_HDL_Optimized_out1;

  assign ce_out = clk_enable;

endmodule  // RS

