// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\DVB-S\HDL_Gen\DVBS\RS_Ctrl.v
// Created: 2024-06-09 10:16:42
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RS_Ctrl
// Source Path: DVBS/DataSource_Scrambler/RS_Ctrl
// Hierarchy Level: 1
// Model version: 1.64
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RS_Ctrl
          (clk,
           reset_n,
           enb,
           DataGenEn,
           simStart,
           simEnd,
           simEN);


  input   clk;
  input   reset_n;
  input   enb;
  input   DataGenEn;
  output  simStart;
  output  simEnd;
  output  simEN;


  wire [31:0] count_step;  // uint32
  wire [31:0] count_from;  // uint32
  reg [31:0] HDL_Counter1_out1;  // uint32
  wire [31:0] count;  // uint32
  wire need_to_wrap;
  wire [31:0] count_value;  // uint32
  wire [31:0] count_1;  // uint32
  wire [7:0] prelookup_idx;  // uint8
  wire [7:0] alpha1_D_Lookup_Table1_table_data [0:203];  // ufix8 [204]
  wire [7:0] alpha1_D_Lookup_Table1_out1;  // uint8
  wire DATA_IN1_out1;
  wire [31:0] count_step_1;  // uint32
  wire [31:0] count_from_1;  // uint32
  reg [31:0] HDL_Counter2_out1;  // uint32
  wire [31:0] count_2;  // uint32
  wire need_to_wrap_1;
  wire [31:0] count_value_1;  // uint32
  wire [31:0] count_3;  // uint32
  wire [7:0] prelookup_idx_1;  // uint8
  wire [7:0] alpha1_D_Lookup_Table2_table_data [0:203];  // ufix8 [204]
  wire [7:0] alpha1_D_Lookup_Table2_out1;  // uint8
  wire DATA_IN2_out1;
  wire [31:0] count_step_2;  // uint32
  wire [31:0] count_from_2;  // uint32
  reg [31:0] HDL_Counter3_out1;  // uint32
  wire [31:0] count_4;  // uint32
  wire need_to_wrap_2;
  wire [31:0] count_value_2;  // uint32
  wire [31:0] count_5;  // uint32
  wire [7:0] prelookup_idx_2;  // uint8
  wire [7:0] alpha1_D_Lookup_Table3_table_data [0:203];  // ufix8 [204]
  wire [7:0] alpha1_D_Lookup_Table3_out1;  // uint8
  wire DATA_IN3_out1;


  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 203
  assign count_step = 32'b00000000000000000000000000000001;



  assign count_from = 32'b00000000000000000000000000000000;



  assign count = HDL_Counter1_out1 + count_step;



  assign need_to_wrap = HDL_Counter1_out1 == 32'b00000000000000000000000011001011;



  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);



  assign count_1 = (DataGenEn == 1'b0 ? HDL_Counter1_out1 :
              count_value);



  always @(posedge clk or negedge reset_n)
    begin : HDL_Counter1_process
      if (reset_n == 1'b0) begin
        HDL_Counter1_out1 <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          HDL_Counter1_out1 <= count_1;
        end
      end
    end



  assign prelookup_idx = (HDL_Counter1_out1 == 32'b00000000000000000000000000000000 ? 8'b00000000 :
              (HDL_Counter1_out1 >= 32'b00000000000000000000000011001011 ? 8'b11001011 :
              HDL_Counter1_out1[7:0]));



  assign alpha1_D_Lookup_Table1_table_data[0] = 8'b00000001;
  assign alpha1_D_Lookup_Table1_table_data[1] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[2] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[3] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[4] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[5] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[6] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[7] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[8] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[9] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[10] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[11] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[12] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[13] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[14] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[15] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[16] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[17] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[18] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[19] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[20] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[21] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[22] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[23] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[24] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[25] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[26] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[27] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[28] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[29] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[30] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[31] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[32] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[33] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[34] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[35] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[36] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[37] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[38] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[39] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[40] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[41] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[42] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[43] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[44] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[45] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[46] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[47] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[48] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[49] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[50] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[51] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[52] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[53] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[54] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[55] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[56] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[57] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[58] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[59] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[60] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[61] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[62] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[63] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[64] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[65] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[66] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[67] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[68] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[69] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[70] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[71] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[72] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[73] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[74] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[75] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[76] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[77] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[78] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[79] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[80] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[81] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[82] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[83] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[84] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[85] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[86] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[87] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[88] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[89] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[90] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[91] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[92] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[93] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[94] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[95] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[96] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[97] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[98] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[99] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[100] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[101] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[102] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[103] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[104] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[105] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[106] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[107] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[108] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[109] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[110] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[111] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[112] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[113] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[114] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[115] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[116] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[117] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[118] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[119] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[120] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[121] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[122] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[123] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[124] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[125] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[126] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[127] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[128] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[129] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[130] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[131] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[132] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[133] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[134] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[135] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[136] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[137] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[138] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[139] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[140] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[141] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[142] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[143] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[144] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[145] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[146] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[147] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[148] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[149] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[150] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[151] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[152] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[153] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[154] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[155] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[156] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[157] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[158] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[159] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[160] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[161] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[162] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[163] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[164] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[165] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[166] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[167] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[168] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[169] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[170] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[171] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[172] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[173] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[174] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[175] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[176] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[177] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[178] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[179] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[180] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[181] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[182] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[183] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[184] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[185] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[186] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[187] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[188] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[189] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[190] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[191] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[192] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[193] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[194] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[195] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[196] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[197] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[198] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[199] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[200] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[201] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[202] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_table_data[203] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_out1 = alpha1_D_Lookup_Table1_table_data[prelookup_idx];



  assign DATA_IN1_out1 = (alpha1_D_Lookup_Table1_out1 != 8'b00000000 ? 1'b1 :
              1'b0);



  assign simStart = DATA_IN1_out1;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 203
  assign count_step_1 = 32'b00000000000000000000000000000001;



  assign count_from_1 = 32'b00000000000000000000000000000000;



  assign count_2 = HDL_Counter2_out1 + count_step_1;



  assign need_to_wrap_1 = HDL_Counter2_out1 == 32'b00000000000000000000000011001011;



  assign count_value_1 = (need_to_wrap_1 == 1'b0 ? count_2 :
              count_from_1);



  assign count_3 = (DataGenEn == 1'b0 ? HDL_Counter2_out1 :
              count_value_1);



  always @(posedge clk or negedge reset_n)
    begin : HDL_Counter2_process
      if (reset_n == 1'b0) begin
        HDL_Counter2_out1 <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          HDL_Counter2_out1 <= count_3;
        end
      end
    end



  assign prelookup_idx_1 = (HDL_Counter2_out1 == 32'b00000000000000000000000000000000 ? 8'b00000000 :
              (HDL_Counter2_out1 >= 32'b00000000000000000000000011001011 ? 8'b11001011 :
              HDL_Counter2_out1[7:0]));



  assign alpha1_D_Lookup_Table2_table_data[0] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[1] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[2] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[3] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[4] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[5] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[6] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[7] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[8] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[9] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[10] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[11] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[12] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[13] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[14] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[15] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[16] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[17] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[18] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[19] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[20] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[21] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[22] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[23] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[24] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[25] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[26] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[27] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[28] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[29] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[30] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[31] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[32] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[33] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[34] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[35] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[36] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[37] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[38] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[39] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[40] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[41] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[42] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[43] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[44] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[45] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[46] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[47] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[48] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[49] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[50] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[51] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[52] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[53] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[54] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[55] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[56] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[57] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[58] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[59] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[60] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[61] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[62] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[63] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[64] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[65] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[66] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[67] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[68] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[69] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[70] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[71] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[72] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[73] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[74] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[75] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[76] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[77] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[78] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[79] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[80] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[81] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[82] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[83] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[84] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[85] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[86] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[87] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[88] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[89] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[90] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[91] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[92] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[93] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[94] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[95] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[96] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[97] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[98] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[99] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[100] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[101] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[102] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[103] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[104] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[105] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[106] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[107] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[108] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[109] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[110] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[111] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[112] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[113] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[114] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[115] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[116] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[117] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[118] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[119] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[120] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[121] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[122] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[123] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[124] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[125] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[126] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[127] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[128] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[129] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[130] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[131] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[132] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[133] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[134] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[135] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[136] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[137] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[138] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[139] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[140] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[141] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[142] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[143] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[144] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[145] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[146] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[147] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[148] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[149] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[150] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[151] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[152] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[153] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[154] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[155] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[156] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[157] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[158] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[159] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[160] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[161] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[162] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[163] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[164] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[165] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[166] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[167] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[168] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[169] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[170] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[171] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[172] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[173] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[174] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[175] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[176] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[177] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[178] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[179] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[180] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[181] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[182] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[183] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[184] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[185] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[186] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[187] = 8'b00000001;
  assign alpha1_D_Lookup_Table2_table_data[188] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[189] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[190] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[191] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[192] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[193] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[194] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[195] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[196] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[197] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[198] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[199] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[200] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[201] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[202] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_table_data[203] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_out1 = alpha1_D_Lookup_Table2_table_data[prelookup_idx_1];



  assign DATA_IN2_out1 = (alpha1_D_Lookup_Table2_out1 != 8'b00000000 ? 1'b1 :
              1'b0);



  assign simEnd = DATA_IN2_out1;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 203
  assign count_step_2 = 32'b00000000000000000000000000000001;



  assign count_from_2 = 32'b00000000000000000000000000000000;



  assign count_4 = HDL_Counter3_out1 + count_step_2;



  assign need_to_wrap_2 = HDL_Counter3_out1 == 32'b00000000000000000000000011001011;



  assign count_value_2 = (need_to_wrap_2 == 1'b0 ? count_4 :
              count_from_2);



  assign count_5 = (DataGenEn == 1'b0 ? HDL_Counter3_out1 :
              count_value_2);



  always @(posedge clk or negedge reset_n)
    begin : HDL_Counter3_process
      if (reset_n == 1'b0) begin
        HDL_Counter3_out1 <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          HDL_Counter3_out1 <= count_5;
        end
      end
    end



  assign prelookup_idx_2 = (HDL_Counter3_out1 == 32'b00000000000000000000000000000000 ? 8'b00000000 :
              (HDL_Counter3_out1 >= 32'b00000000000000000000000011001011 ? 8'b11001011 :
              HDL_Counter3_out1[7:0]));



  assign alpha1_D_Lookup_Table3_table_data[0] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[1] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[2] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[3] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[4] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[5] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[6] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[7] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[8] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[9] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[10] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[11] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[12] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[13] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[14] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[15] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[16] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[17] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[18] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[19] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[20] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[21] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[22] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[23] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[24] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[25] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[26] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[27] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[28] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[29] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[30] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[31] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[32] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[33] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[34] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[35] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[36] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[37] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[38] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[39] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[40] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[41] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[42] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[43] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[44] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[45] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[46] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[47] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[48] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[49] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[50] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[51] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[52] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[53] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[54] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[55] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[56] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[57] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[58] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[59] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[60] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[61] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[62] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[63] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[64] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[65] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[66] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[67] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[68] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[69] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[70] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[71] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[72] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[73] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[74] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[75] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[76] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[77] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[78] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[79] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[80] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[81] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[82] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[83] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[84] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[85] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[86] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[87] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[88] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[89] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[90] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[91] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[92] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[93] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[94] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[95] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[96] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[97] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[98] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[99] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[100] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[101] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[102] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[103] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[104] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[105] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[106] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[107] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[108] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[109] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[110] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[111] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[112] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[113] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[114] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[115] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[116] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[117] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[118] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[119] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[120] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[121] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[122] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[123] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[124] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[125] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[126] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[127] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[128] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[129] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[130] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[131] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[132] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[133] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[134] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[135] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[136] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[137] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[138] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[139] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[140] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[141] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[142] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[143] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[144] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[145] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[146] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[147] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[148] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[149] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[150] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[151] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[152] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[153] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[154] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[155] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[156] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[157] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[158] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[159] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[160] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[161] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[162] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[163] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[164] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[165] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[166] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[167] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[168] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[169] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[170] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[171] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[172] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[173] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[174] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[175] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[176] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[177] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[178] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[179] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[180] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[181] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[182] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[183] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[184] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[185] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[186] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[187] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_table_data[188] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_table_data[189] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_table_data[190] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_table_data[191] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_table_data[192] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_table_data[193] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_table_data[194] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_table_data[195] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_table_data[196] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_table_data[197] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_table_data[198] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_table_data[199] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_table_data[200] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_table_data[201] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_table_data[202] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_table_data[203] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_out1 = alpha1_D_Lookup_Table3_table_data[prelookup_idx_2];



  assign DATA_IN3_out1 = (alpha1_D_Lookup_Table3_out1 != 8'b00000000 ? 1'b1 :
              1'b0);



  assign simEN = DATA_IN3_out1;

endmodule  // RS_Ctrl

