// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\DVB-S\HDL_Gen\DVBS\RS_Enc.v
// Created: 2024-06-09 10:18:37
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 5e-09
// Target subsystem base rate: 5e-09
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        5e-09
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// RS_Out                        ce_out        5e-09
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RS_Enc
// Source Path: DVBS/RS_Enc
// Hierarchy Level: 0
// Model version: 1.64
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RS_Enc
          (clk,
           reset_n,
           clk_enable,
           Trigger,
           RS_In,
           RS_Start,
           RS_End,
           RS_VLD,
           ce_out,
           RS_Out);


  input   clk;
  input   reset_n;
  input   clk_enable;
  input   Trigger;
  input   [7:0] RS_In;  // uint8
  input   RS_Start;
  input   RS_End;
  input   RS_VLD;
  output  ce_out;
  output  [7:0] RS_Out;  // uint8


  wire [7:0] RS_out1;  // uint8


  RS u_RS (.clk(clk),
           .reset_n(reset_n),
           .enb(clk_enable),
           .RS_In(RS_In),  // uint8
           .RS_Start(RS_Start),
           .RS_End(RS_End),
           .RS_VLD(RS_VLD),
           .Trigger(Trigger),
           .RS_Out(RS_out1)  // uint8
           );

  assign RS_Out = RS_out1;

  assign ce_out = clk_enable;

endmodule  // RS_Enc

