// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\FPGA_myself\DVB-S\HDL_Gen\DVBS\SimDataAndCtrlIN1.v
// Created: 2024-05-15 16:39:42
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1.5625e-06
// Target subsystem base rate: 0.0001
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.0001
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// simDataIn                     ce_out        0.0001
// simStart                      ce_out        0.0001
// simEnd                        ce_out        0.0001
// simVld                        ce_out        0.0001
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SimDataAndCtrlIN1
// Source Path: DVBS/SimDataAndCtrlIN1
// Hierarchy Level: 0
// Model version: 1.47
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SimDataAndCtrlIN1
          (clk,
           reset_n,
           clk_enable,
           ce_out,
           simDataIn,
           simStart,
           simEnd,
           simVld);


  input   clk;
  input   reset_n;
  input   clk_enable;
  output  ce_out;
  output  [7:0] simDataIn;  // uint8
  output  simStart;
  output  simEnd;
  output  simVld;


  wire enb_1_64_0;
  wire [7:0] count_step;  // uint8
  wire [7:0] count_from;  // uint8
  reg [7:0] HDL_Counter_out1;  // uint8
  wire [7:0] count;  // uint8
  wire need_to_wrap;
  wire [7:0] count_value;  // uint8
  wire [7:0] prelookup_idx;  // uint8
  wire [7:0] out;  // uint8
  reg [7:0] alpha1_D_Lookup_Table_out1;  // uint8
  wire [7:0] prelookup_idx_1;  // uint8
  wire [7:0] alpha1_D_Lookup_Table1_1 [0:204];  // ufix8 [205]
  wire [7:0] out_1;  // uint8
  reg [7:0] alpha1_D_Lookup_Table1_out1;  // uint8
  wire DATA_IN1_out1;
  wire [7:0] prelookup_idx_2;  // uint8
  wire [7:0] alpha1_D_Lookup_Table2_1 [0:204];  // ufix8 [205]
  wire [7:0] out_2;  // uint8
  reg [7:0] alpha1_D_Lookup_Table2_out1;  // uint8
  wire DATA_IN2_out1;
  wire [7:0] prelookup_idx_3;  // uint8
  wire [7:0] alpha1_D_Lookup_Table3_1 [0:204];  // ufix8 [205]
  wire [7:0] out_3;  // uint8
  reg [7:0] alpha1_D_Lookup_Table3_out1;  // uint8
  wire DATA_IN3_out1;

  initial begin
    alpha1_D_Lookup_Table_out1 = 8'b00000000;
    alpha1_D_Lookup_Table1_out1 = 8'b00000000;
    alpha1_D_Lookup_Table2_out1 = 8'b00000000;
    alpha1_D_Lookup_Table3_out1 = 8'b00000000;
  end

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 187
  assign count_step = 8'b00000001;



  assign count_from = 8'b00000000;



  assign enb_1_64_0 = clk_enable;

  assign count = HDL_Counter_out1 + count_step;



  assign need_to_wrap = HDL_Counter_out1 == 8'b10111011;



  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);



  always @(posedge clk or negedge reset_n)
    begin : HDL_Counter_process
      if (reset_n == 1'b0) begin
        HDL_Counter_out1 <= 8'b00000000;
      end
      else begin
        if (enb_1_64_0) begin
          HDL_Counter_out1 <= count_value;
        end
      end
    end



  assign prelookup_idx = (HDL_Counter_out1 == 8'b00000000 ? 8'b00000000 :
              (HDL_Counter_out1 >= 8'b10111011 ? 8'b10111011 :
              HDL_Counter_out1));



  assign out = 8'b00000001;



  always @(posedge clk)
    begin : PipelineRegister_process
      if (enb_1_64_0) begin
        alpha1_D_Lookup_Table_out1 <= out;
      end
    end



  assign simDataIn = alpha1_D_Lookup_Table_out1;

  assign prelookup_idx_1 = (HDL_Counter_out1 == 8'b00000000 ? 8'b00000000 :
              (HDL_Counter_out1 >= 8'b11001100 ? 8'b11001100 :
              HDL_Counter_out1));



  assign alpha1_D_Lookup_Table1_1[0] = 8'b00000001;
  assign alpha1_D_Lookup_Table1_1[1] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[2] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[3] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[4] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[5] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[6] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[7] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[8] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[9] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[10] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[11] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[12] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[13] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[14] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[15] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[16] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[17] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[18] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[19] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[20] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[21] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[22] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[23] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[24] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[25] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[26] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[27] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[28] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[29] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[30] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[31] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[32] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[33] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[34] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[35] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[36] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[37] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[38] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[39] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[40] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[41] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[42] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[43] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[44] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[45] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[46] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[47] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[48] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[49] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[50] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[51] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[52] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[53] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[54] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[55] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[56] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[57] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[58] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[59] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[60] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[61] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[62] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[63] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[64] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[65] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[66] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[67] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[68] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[69] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[70] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[71] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[72] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[73] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[74] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[75] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[76] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[77] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[78] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[79] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[80] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[81] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[82] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[83] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[84] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[85] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[86] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[87] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[88] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[89] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[90] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[91] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[92] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[93] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[94] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[95] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[96] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[97] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[98] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[99] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[100] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[101] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[102] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[103] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[104] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[105] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[106] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[107] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[108] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[109] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[110] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[111] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[112] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[113] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[114] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[115] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[116] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[117] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[118] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[119] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[120] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[121] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[122] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[123] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[124] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[125] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[126] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[127] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[128] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[129] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[130] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[131] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[132] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[133] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[134] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[135] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[136] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[137] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[138] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[139] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[140] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[141] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[142] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[143] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[144] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[145] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[146] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[147] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[148] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[149] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[150] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[151] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[152] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[153] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[154] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[155] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[156] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[157] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[158] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[159] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[160] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[161] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[162] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[163] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[164] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[165] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[166] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[167] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[168] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[169] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[170] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[171] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[172] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[173] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[174] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[175] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[176] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[177] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[178] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[179] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[180] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[181] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[182] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[183] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[184] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[185] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[186] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[187] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[188] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[189] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[190] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[191] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[192] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[193] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[194] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[195] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[196] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[197] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[198] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[199] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[200] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[201] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[202] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[203] = 8'b00000000;
  assign alpha1_D_Lookup_Table1_1[204] = 8'b00000001;
  assign out_1 = alpha1_D_Lookup_Table1_1[prelookup_idx_1];



  always @(posedge clk)
    begin : PipelineRegister_1_process
      if (enb_1_64_0) begin
        alpha1_D_Lookup_Table1_out1 <= out_1;
      end
    end



  assign DATA_IN1_out1 = (alpha1_D_Lookup_Table1_out1 != 8'b00000000 ? 1'b1 :
              1'b0);



  assign simStart = DATA_IN1_out1;

  assign prelookup_idx_2 = (HDL_Counter_out1 == 8'b00000000 ? 8'b00000000 :
              (HDL_Counter_out1 >= 8'b11001100 ? 8'b11001100 :
              HDL_Counter_out1));



  assign alpha1_D_Lookup_Table2_1[0] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[1] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[2] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[3] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[4] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[5] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[6] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[7] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[8] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[9] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[10] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[11] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[12] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[13] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[14] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[15] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[16] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[17] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[18] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[19] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[20] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[21] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[22] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[23] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[24] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[25] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[26] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[27] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[28] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[29] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[30] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[31] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[32] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[33] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[34] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[35] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[36] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[37] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[38] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[39] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[40] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[41] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[42] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[43] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[44] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[45] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[46] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[47] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[48] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[49] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[50] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[51] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[52] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[53] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[54] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[55] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[56] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[57] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[58] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[59] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[60] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[61] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[62] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[63] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[64] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[65] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[66] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[67] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[68] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[69] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[70] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[71] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[72] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[73] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[74] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[75] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[76] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[77] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[78] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[79] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[80] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[81] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[82] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[83] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[84] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[85] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[86] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[87] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[88] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[89] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[90] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[91] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[92] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[93] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[94] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[95] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[96] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[97] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[98] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[99] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[100] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[101] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[102] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[103] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[104] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[105] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[106] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[107] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[108] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[109] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[110] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[111] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[112] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[113] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[114] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[115] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[116] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[117] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[118] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[119] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[120] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[121] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[122] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[123] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[124] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[125] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[126] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[127] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[128] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[129] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[130] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[131] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[132] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[133] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[134] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[135] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[136] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[137] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[138] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[139] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[140] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[141] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[142] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[143] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[144] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[145] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[146] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[147] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[148] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[149] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[150] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[151] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[152] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[153] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[154] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[155] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[156] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[157] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[158] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[159] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[160] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[161] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[162] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[163] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[164] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[165] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[166] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[167] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[168] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[169] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[170] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[171] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[172] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[173] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[174] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[175] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[176] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[177] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[178] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[179] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[180] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[181] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[182] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[183] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[184] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[185] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[186] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[187] = 8'b00000001;
  assign alpha1_D_Lookup_Table2_1[188] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[189] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[190] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[191] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[192] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[193] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[194] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[195] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[196] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[197] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[198] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[199] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[200] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[201] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[202] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[203] = 8'b00000000;
  assign alpha1_D_Lookup_Table2_1[204] = 8'b00000000;
  assign out_2 = alpha1_D_Lookup_Table2_1[prelookup_idx_2];



  always @(posedge clk)
    begin : PipelineRegister_2_process
      if (enb_1_64_0) begin
        alpha1_D_Lookup_Table2_out1 <= out_2;
      end
    end



  assign DATA_IN2_out1 = (alpha1_D_Lookup_Table2_out1 != 8'b00000000 ? 1'b1 :
              1'b0);



  assign simEnd = DATA_IN2_out1;

  assign prelookup_idx_3 = (HDL_Counter_out1 == 8'b00000000 ? 8'b00000000 :
              (HDL_Counter_out1 >= 8'b11001100 ? 8'b11001100 :
              HDL_Counter_out1));



  assign alpha1_D_Lookup_Table3_1[0] = 8'b00000001;
  assign alpha1_D_Lookup_Table3_1[1] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[2] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[3] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[4] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[5] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[6] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[7] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[8] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[9] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[10] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[11] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[12] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[13] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[14] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[15] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[16] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[17] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[18] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[19] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[20] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[21] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[22] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[23] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[24] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[25] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[26] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[27] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[28] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[29] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[30] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[31] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[32] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[33] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[34] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[35] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[36] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[37] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[38] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[39] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[40] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[41] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[42] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[43] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[44] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[45] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[46] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[47] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[48] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[49] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[50] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[51] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[52] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[53] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[54] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[55] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[56] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[57] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[58] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[59] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[60] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[61] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[62] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[63] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[64] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[65] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[66] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[67] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[68] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[69] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[70] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[71] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[72] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[73] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[74] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[75] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[76] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[77] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[78] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[79] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[80] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[81] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[82] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[83] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[84] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[85] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[86] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[87] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[88] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[89] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[90] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[91] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[92] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[93] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[94] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[95] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[96] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[97] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[98] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[99] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[100] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[101] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[102] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[103] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[104] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[105] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[106] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[107] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[108] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[109] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[110] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[111] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[112] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[113] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[114] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[115] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[116] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[117] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[118] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[119] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[120] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[121] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[122] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[123] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[124] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[125] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[126] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[127] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[128] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[129] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[130] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[131] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[132] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[133] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[134] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[135] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[136] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[137] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[138] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[139] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[140] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[141] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[142] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[143] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[144] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[145] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[146] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[147] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[148] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[149] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[150] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[151] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[152] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[153] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[154] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[155] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[156] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[157] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[158] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[159] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[160] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[161] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[162] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[163] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[164] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[165] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[166] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[167] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[168] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[169] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[170] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[171] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[172] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[173] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[174] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[175] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[176] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[177] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[178] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[179] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[180] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[181] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[182] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[183] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[184] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[185] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[186] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[187] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[188] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[189] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[190] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[191] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[192] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[193] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[194] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[195] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[196] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[197] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[198] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[199] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[200] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[201] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[202] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[203] = 8'b00000000;
  assign alpha1_D_Lookup_Table3_1[204] = 8'b00000001;
  assign out_3 = alpha1_D_Lookup_Table3_1[prelookup_idx_3];



  always @(posedge clk)
    begin : PipelineRegister_3_process
      if (enb_1_64_0) begin
        alpha1_D_Lookup_Table3_out1 <= out_3;
      end
    end



  assign DATA_IN3_out1 = (alpha1_D_Lookup_Table3_out1 != 8'b00000000 ? 1'b1 :
              1'b0);



  assign simVld = DATA_IN3_out1;

  assign ce_out = clk_enable;

endmodule  // SimDataAndCtrlIN1

