// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\FPGA_myself\DVB-S\HDL_Gen\DVBS\SinDataIn.v
// Created: 2024-05-14 14:50:50
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1.5625e-06
// Target subsystem base rate: 0.0001
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.0001
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1                          ce_out        0.0001
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SinDataIn
// Source Path: DVBS/SinDataIn
// Hierarchy Level: 0
// Model version: 1.44
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SinDataIn
          (clk,
           reset_n,
           clk_enable,
           ce_out,
           Out1);


  input   clk;
  input   reset_n;
  input   clk_enable;
  output  ce_out;
  output  [7:0] Out1;  // uint8


  wire enb_1_64_0;
  wire [7:0] count_step;  // uint8
  wire [7:0] count_from;  // uint8
  reg [7:0] HDL_Counter_out1;  // uint8
  wire [7:0] count;  // uint8
  wire need_to_wrap;
  wire [7:0] count_value;  // uint8
  wire [7:0] prelookup_idx;  // uint8
  wire [7:0] out;  // uint8
  reg [7:0] alpha1_D_Lookup_Table_out1;  // uint8

  initial begin
    alpha1_D_Lookup_Table_out1 = 8'b00000000;
  end

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 187
  assign count_step = 8'b00000001;



  assign count_from = 8'b00000000;



  assign enb_1_64_0 = clk_enable;

  assign count = HDL_Counter_out1 + count_step;



  assign need_to_wrap = HDL_Counter_out1 == 8'b10111011;



  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);



  always @(posedge clk or negedge reset_n)
    begin : HDL_Counter_process
      if (reset_n == 1'b0) begin
        HDL_Counter_out1 <= 8'b00000000;
      end
      else begin
        if (enb_1_64_0) begin
          HDL_Counter_out1 <= count_value;
        end
      end
    end



  assign prelookup_idx = (HDL_Counter_out1 == 8'b00000000 ? 8'b00000000 :
              (HDL_Counter_out1 >= 8'b10111011 ? 8'b10111011 :
              HDL_Counter_out1));



  assign out = 8'b00000001;



  always @(posedge clk)
    begin : PipelineRegister_process
      if (enb_1_64_0) begin
        alpha1_D_Lookup_Table_out1 <= out;
      end
    end



  assign Out1 = alpha1_D_Lookup_Table_out1;

  assign ce_out = clk_enable;

endmodule  // SinDataIn

