# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Git_Repository/DVB-S/Vivado_BU01/Vivado2.srcs/sources_1/bd/top/ip/top_c_addsub_0_0/top_c_addsub_0_0.xci
# IP: The module: 'top_c_addsub_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Git_Repository/DVB-S/Vivado_BU01/Vivado2.gen/sources_1/bd/top/ip/top_c_addsub_0_0/top_c_addsub_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_c_addsub_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: F:/Git_Repository/DVB-S/Vivado_BU01/Vivado2.srcs/sources_1/bd/top/ip/top_c_addsub_0_0/top_c_addsub_0_0.xci
# IP: The module: 'top_c_addsub_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Git_Repository/DVB-S/Vivado_BU01/Vivado2.gen/sources_1/bd/top/ip/top_c_addsub_0_0/top_c_addsub_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_c_addsub_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
