set_property IOSTANDARD LVCMOS33 [get_ports clk_0]
set_property IOSTANDARD LVCMOS33 [get_ports reset_n_0]
set_property PACKAGE_PIN U18 [get_ports clk_0]
set_property PACKAGE_PIN N15 [get_ports reset_n_0]
create_clock -period 100.000 -name clk_0 -waveform {0.000 50.000} [get_ports clk_0]





set_property PACKAGE_PIN Y6 [get_ports {S_0[18]}]
set_property PACKAGE_PIN Y9 [get_ports {S_0[17]}]
set_property PACKAGE_PIN Y8 [get_ports {S_0[16]}]
set_property PACKAGE_PIN V8 [get_ports {S_0[15]}]
set_property PACKAGE_PIN W8 [get_ports {S_0[14]}]
set_property PACKAGE_PIN W10 [get_ports {S_0[13]}]
set_property PACKAGE_PIN W9 [get_ports {S_0[12]}]
set_property PACKAGE_PIN U9 [get_ports {S_0[11]}]
set_property PACKAGE_PIN U8 [get_ports {S_0[10]}]
set_property PACKAGE_PIN W11 [get_ports {S_0[9]}]
set_property PACKAGE_PIN Y11 [get_ports {S_0[8]}]
set_property PACKAGE_PIN T5 [get_ports {S_0[7]}]
set_property PACKAGE_PIN U5 [get_ports {S_0[6]}]
set_property PACKAGE_PIN Y12 [get_ports {S_0[5]}]
set_property PACKAGE_PIN Y13 [get_ports {S_0[4]}]
set_property PACKAGE_PIN V11 [get_ports {S_0[3]}]
set_property PACKAGE_PIN V10 [get_ports {S_0[2]}]
set_property PACKAGE_PIN V6 [get_ports {S_0[1]}]
set_property PACKAGE_PIN W6 [get_ports {S_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_0[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_0[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_0[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_0[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_0[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_0[0]}]

set_operating_conditions -grade extended
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]

set_property PACKAGE_PIN U13 [get_ports {S_0[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_0[19]}]
