######################################################################
#
# File name : top_tb_wave.do
# Created on: Sun Jun 09 11:17:03 +0800 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
