######################################################################
#
# File name : top_tb_wave.do
# Created on: Thu Jun 06 14:29:57 +0800 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
