set_property SRC_FILE_INFO {cfile:F:/Git_Repository/FPGA_myself/DVB-S/Vivado2/Vivado2.srcs/constrs_1/new/topCons.xdc rfile:../../../Vivado2.srcs/constrs_1/new/topCons.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports clk_0]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N15 [get_ports reset_n_0]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports OUT_port_0]
