// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\DVB-S\HDL_Gen\DVBS_axi4stream\hdlsrc\DVBS_AXI4Stream\Con_Encoder.v
// Created: 2024-06-07 16:51:12
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Con_Encoder
// Source Path: DVBS_AXI4Stream/DVB-S/Con_Encoder
// Hierarchy Level: 1
// Model version: 1.65
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ps

module Con_Encoder
          (clk,
           reset_n,
           enb,
           In1,
           VldIn,
           ConvOut_0,
           ConvOut_1);


  input   clk;
  input   reset_n;
  input   enb;
  input   In1;
  input   VldIn;
  output  ConvOut_0;  // boolean
  output  ConvOut_1;  // boolean


  reg  VldIn_1;
  wire Convolutional_Encoder_out1_0;
  wire Convolutional_Encoder_out1_1;


  always @(posedge clk or negedge reset_n)
    begin : delayMatch_process
      if (reset_n == 1'b0) begin
        VldIn_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          VldIn_1 <= VldIn;
        end
      end
    end



  Convolutional_Encoder u_Convolutional_Encoder (.clk(clk),
                                                 .reset_n(reset_n),
                                                 .enb(enb),
                                                 .in0(In1),
                                                 .in1(VldIn_1),
                                                 .out0_0(Convolutional_Encoder_out1_0),  // boolean
                                                 .out0_1(Convolutional_Encoder_out1_1)  // boolean
                                                 );

  assign ConvOut_0 = Convolutional_Encoder_out1_0;

  assign ConvOut_1 = Convolutional_Encoder_out1_1;

endmodule  // Con_Encoder

