// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\DVB-S\HDL_Gen\DVBS_axi4stream\hdlsrc\DVBS_AXI4Stream\Interleaver.v
// Created: 2024-06-07 16:51:13
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Interleaver
// Source Path: DVBS_AXI4Stream/DVB-S/Interleaver
// Hierarchy Level: 1
// Model version: 1.65
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ps

module Interleaver
          (clk,
           reset_n,
           enb,
           Trigger,
           DataIn,
           InterOut);


  input   clk;
  input   reset_n;
  input   enb;
  input   Trigger;
  input   [7:0] DataIn;  // uint8
  output  [7:0] InterOut;  // uint8


  reg  Trigger_1;
  wire [7:0] Con_Interleaver_out1;  // uint8


  always @(posedge clk or negedge reset_n)
    begin : delayMatch_process
      if (reset_n == 1'b0) begin
        Trigger_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Trigger_1 <= Trigger;
        end
      end
    end



  Con_Interleaver u_Con_Interleaver (.clk(clk),
                                     .reset_n(reset_n),
                                     .enb(enb),
                                     .In1(DataIn),  // uint8
                                     .Trigger(Trigger_1),
                                     .Out1(Con_Interleaver_out1)  // uint8
                                     );

  assign InterOut = Con_Interleaver_out1;

endmodule  // Interleaver

