// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\DVB-S\HDL_Gen\DVBS_axi4stream\hdlsrc\DVBS_AXI4Stream\RS.v
// Created: 2024-06-07 16:51:13
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RS
// Source Path: DVBS_AXI4Stream/DVB-S/RS_Enc/RS
// Hierarchy Level: 2
// Model version: 1.65
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ps

module RS
          (clk,
           reset_n,
           enb,
           RS_In,
           RS_Start,
           RS_End,
           RS_VLD,
           Trigger,
           RS_Out);


  input   clk;
  input   reset_n;
  input   enb;
  input   [7:0] RS_In;  // uint8
  input   RS_Start;
  input   RS_End;
  input   RS_VLD;
  input   Trigger;
  output  [7:0] RS_Out;  // uint8


  reg  Trigger_delayed;
  wire Trigger_delayed_inverted;
  wire Trigger_emulated;
  reg  Trigger_emulated_1;
  wire enb_gated;
  wire [7:0] Integer_Input_RS_Encoder_HDL_Optimized_out1;  // uint8
  wire [7:0] Integer_Input_RS_Encoder_HDL_Optimized_out1_1;  // uint8
  reg [7:0] Integer_Input_RS_Encoder_HDL_Optimized_out1_last_value;  // uint8


  always @(posedge clk or negedge reset_n)
    begin : Trigger_delay_process
      if (reset_n == 1'b0) begin
        Trigger_delayed <= 1'b1;
      end
      else begin
        if (enb) begin
          Trigger_delayed <= Trigger;
        end
      end
    end



  assign Trigger_delayed_inverted =  ~ Trigger_delayed;



  assign Trigger_emulated = Trigger_delayed_inverted & Trigger;



  always @(posedge clk or negedge reset_n)
    begin : delayMatch_process
      if (reset_n == 1'b0) begin
        Trigger_emulated_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Trigger_emulated_1 <= Trigger_emulated;
        end
      end
    end



  assign enb_gated = Trigger_emulated_1 && enb;

  Integer_Input_RS_Encoder_HDL_Optimized u_Integer_Input_RS_Encoder_HDL_Optimized (.clk(clk),
                                                                                   .reset_n(reset_n),
                                                                                   .enb(enb_gated),
                                                                                   .Integer_Input_RS_Encoder_HDL_Optimized_in(RS_In),  // uint8
                                                                                   .Integer_Input_RS_Encoder_HDL_Optimized_start(RS_Start),
                                                                                   .Integer_Input_RS_Encoder_HDL_Optimized_end(RS_End),
                                                                                   .Integer_Input_RS_Encoder_HDL_Optimized_datavalid(RS_VLD),
                                                                                   .Integer_Input_RS_Encoder_HDL_Optimized_out(Integer_Input_RS_Encoder_HDL_Optimized_out1)  // uint8
                                                                                   );

  always @(posedge clk or negedge reset_n)
    begin : out0_bypass_process
      if (reset_n == 1'b0) begin
        Integer_Input_RS_Encoder_HDL_Optimized_out1_last_value <= 8'b00000000;
      end
      else begin
        if (enb_gated) begin
          Integer_Input_RS_Encoder_HDL_Optimized_out1_last_value <= Integer_Input_RS_Encoder_HDL_Optimized_out1_1;
        end
      end
    end



  assign Integer_Input_RS_Encoder_HDL_Optimized_out1_1 = (Trigger_emulated_1 == 1'b0 ? Integer_Input_RS_Encoder_HDL_Optimized_out1_last_value :
              Integer_Input_RS_Encoder_HDL_Optimized_out1);



  assign RS_Out = Integer_Input_RS_Encoder_HDL_Optimized_out1_1;

endmodule  // RS

