// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\DVB-S\HDL_Gen\DVBS_axi4stream\hdlsrc\DVBS_AXI4Stream\RS_Enc.v
// Created: 2024-06-07 16:51:13
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RS_Enc
// Source Path: DVBS_AXI4Stream/DVB-S/RS_Enc
// Hierarchy Level: 1
// Model version: 1.65
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ps

module RS_Enc
          (clk,
           reset_n,
           enb,
           Trigger,
           RS_In,
           RS_Start,
           RS_End,
           RS_VLD,
           RS_Out);


  input   clk;
  input   reset_n;
  input   enb;
  input   Trigger;
  input   [7:0] RS_In;  // uint8
  input   RS_Start;
  input   RS_End;
  input   RS_VLD;
  output  [7:0] RS_Out;  // uint8


  wire [7:0] RS_out1;  // uint8


  RS u_RS (.clk(clk),
           .reset_n(reset_n),
           .enb(enb),
           .RS_In(RS_In),  // uint8
           .RS_Start(RS_Start),
           .RS_End(RS_End),
           .RS_VLD(RS_VLD),
           .Trigger(Trigger),
           .RS_Out(RS_out1)  // uint8
           );

  assign RS_Out = RS_out1;

endmodule  // RS_Enc

