######################################################################
#
# File name : top_tb_compile.do
# Created on: Wed May 15 11:21:57 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\FPGA\\Modelsim2020\\win64\\vlib modelsim_lib/work
F:\\FPGA\\Modelsim2020\\win64\\vlib modelsim_lib/msim

F:\\FPGA\\Modelsim2020\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\FPGA\\Modelsim2020\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\FPGA\\Modelsim2020\\win64\\vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../../HDL_Gen/DVBS/alphaScramble.v" \
"../../../../../HDL_Gen/DVBS/SinDataIn.v" \
"../../../../vivado.ip_user_files/bd/top/ip/top_alphaScramble_0_0/sim/top_alphaScramble_0_0.v" \
"../../../../vivado.ip_user_files/bd/top/ip/top_xlconstant_0_0/sim/top_xlconstant_0_0.v" \
"../../../../vivado.ip_user_files/bd/top/ip/top_SinDataIn_0_0/sim/top_SinDataIn_0_0.v" \
"../../../../vivado.ip_user_files/bd/top/sim/top.v" \
"../../../../vivado.ip_user_files/bd/top/ip/top_sim_clk_gen_0_0/sim/top_sim_clk_gen_0_0.v" \
"../../../../vivado.gen/sources_1/bd/top/hdl/top_wrapper.v" \
"../../../../vivado.srcs/sim_1/new/top_tb.v" \


# compile glbl module
F:\\FPGA\\Modelsim2020\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

