######################################################################
#
# File name : top_tb_wave.do
# Created on: Wed May 15 11:19:53 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
