######################################################################
#
# File name : top_tb_simulate.do
# Created on: Wed May 15 11:21:59 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L xlconstant_v1_1_8 -L sim_clk_gen_v1_0_3 -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.top_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {top_tb_wave.do}

view wave
view structure
view signals

do {top_tb.udo}

run 100us
