######################################################################
#
# File name : top_wrapper_compile.do
# Created on: Thu Apr 18 15:48:16 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\EDA\\modeltech64_10.6d\\win64\\vlib modelsim_lib/work
F:\\EDA\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim

F:\\EDA\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\EDA\\modeltech64_10.6d\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\EDA\\modeltech64_10.6d\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../../DVBS/alpharandomization.v" \
"../../../../../DVBS/Integer_Input_RS_Encoder_HDL_Optimized.v" \
"../../../../../DVBS/RS1.v" \
"../../../../dbvs.srcs/sources_1/new/RS_EN_GEN.v" \
"../../../../dbvs.srcs/sources_1/new/Random_Gen_8.v" \
"../../../../dbvs.ip_user_files/bd/top/ip/top_sim_clk_gen_0_0/sim/top_sim_clk_gen_0_0.v" \
"../../../../dbvs.ip_user_files/bd/top/sim/top.v" \
"../../../../dbvs.ip_user_files/bd/top/ip/top_alpharandomization_0_0/sim/top_alpharandomization_0_0.v" \
"../../../../dbvs.ip_user_files/bd/top/ip/top_xlconstant_0_0/sim/top_xlconstant_0_0.v" \
"../../../../dbvs.ip_user_files/bd/top/ip/top_RS1_0_0/sim/top_RS1_0_0.v" \
"../../../../dbvs.ip_user_files/bd/top/ip/top_RS_EN_GEN_0_0/sim/top_RS_EN_GEN_0_0.v" \
"../../../../dbvs.ip_user_files/bd/top/ip/top_Rand_Gen_8_0_0/sim/top_Rand_Gen_8_0_0.v" \
"../../../../dbvs.ip_user_files/bd/top/ip/top_xlconstant_0_1/sim/top_xlconstant_0_1.v" \
"../../../../dbvs.srcs/sources_1/bd/top/hdl/top_wrapper.v" \


# compile glbl module
F:\\EDA\\modeltech64_10.6d\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

