######################################################################
#
# File name : top_wrapper_simulate.do
# Created on: Thu Apr 18 15:48:18 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L sim_clk_gen_v1_0_2 -L xlconstant_v1_1_5 -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.top_wrapper xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {top_wrapper_wave.do}

view wave
view structure
view signals

do {top_wrapper.udo}

run 1000ns
