######################################################################
#
# File name : top_wrapper_wave.do
# Created on: Thu Apr 18 15:48:18 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
