// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\FPGA_myself\DVB-S\HDL_Gen\waveMulTest\NCO.v
// Created: 2024-05-20 16:36:37
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: NCO
// Source Path: waveMulTest/mulWave/NCO
// Hierarchy Level: 1
// Model version: 1.0
// 
// NCO
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module NCO
          (clk,
           reset,
           enb,
           validIn,
           sine);


  input   clk;
  input   reset;
  input   enb;
  input   validIn;
  output  signed [15:0] sine;  // sfix16_En14


  reg  [4:0] outsel_reg_reg;  // ufix1 [5]
  wire outsel;
  wire signed [15:0] outzero;  // sfix16_En14
  wire signed [19:0] const0;  // sfix20
  wire signed [19:0] pInc;  // sfix20
  wire signed [19:0] validPInc;  // sfix20
  reg signed [19:0] accphase_reg;  // sfix20
  wire signed [19:0] addpInc;  // sfix20
  wire signed [19:0] pOffset;  // sfix20
  wire signed [19:0] accoffset;  // sfix20
  reg signed [19:0] accoffsete_reg;  // sfix20
  wire [3:0] dither;  // ufix4
  wire signed [19:0] casteddither;  // sfix20
  reg signed [19:0] dither_reg;  // sfix20
  wire signed [19:0] accumulator;  // sfix20
  wire [12:0] accQuantized;  // ufix13_E7
  wire signed [15:0] outs;  // sfix16_En14
  wire signed [15:0] validouts;  // sfix16_En14
  reg signed [15:0] sine_1;  // sfix16_En14


  always @(posedge clk or posedge reset)
    begin : outsel_reg_process
      if (reset == 1'b1) begin
        outsel_reg_reg <= {5{1'b0}};
      end
      else begin
        if (enb) begin
          outsel_reg_reg[0] <= validIn;
          outsel_reg_reg[32'sd4:32'sd1] <= outsel_reg_reg[32'sd3:32'sd0];
        end
      end
    end

  assign outsel = outsel_reg_reg[4];



  assign outzero = 16'sb0000000000000000;



  // Constant Zero
  assign const0 = 20'sb00000000000000000000;



  assign pInc = 20'sb00000001010001111011;



  assign validPInc = (validIn == 1'b0 ? const0 :
              pInc);



  // Add phase increment
  assign addpInc = accphase_reg + validPInc;



  // Phase increment accumulator register
  always @(posedge clk or posedge reset)
    begin : AccPhaseRegister_process
      if (reset == 1'b1) begin
        accphase_reg <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          accphase_reg <= addpInc;
        end
      end
    end



  assign pOffset = 20'sb00000000000000000000;



  // Add phase offset
  assign accoffset = accphase_reg + pOffset;



  // Phase offset accumulator register
  always @(posedge clk or posedge reset)
    begin : AccOffsetRegister_process
      if (reset == 1'b1) begin
        accoffsete_reg <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          accoffsete_reg <= accoffset;
        end
      end
    end



  DitherGen u_dither_inst (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .validIn(validIn),
                           .dither(dither)  // ufix4
                           );

  assign casteddither = {16'b0, dither};



  // Dither input register
  always @(posedge clk or posedge reset)
    begin : DitherRegister_process
      if (reset == 1'b1) begin
        dither_reg <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          dither_reg <= casteddither;
        end
      end
    end



  // Add dither
  assign accumulator = accoffsete_reg + dither_reg;



  // Phase quantization
  assign accQuantized = accumulator[19:7];



  WaveformGen u_Wave_inst (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .phaseIdx(accQuantized),  // ufix13_E7
                           .sine(outs)  // sfix16_En14
                           );

  assign validouts = (outsel == 1'b0 ? outzero :
              outs);



  // Output register
  always @(posedge clk or posedge reset)
    begin : OutputRegister_process
      if (reset == 1'b1) begin
        sine_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          sine_1 <= validouts;
        end
      end
    end



  assign sine = sine_1;

endmodule  // NCO

