// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\FPGA_myself\DVB-S\HDL_Gen\waveMulTest\WaveformGen.v
// Created: 2024-05-20 16:36:37
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: WaveformGen
// Source Path: waveMulTest/mulWave/NCO/WaveformGen
// Hierarchy Level: 2
// Model version: 1.0
// 
// Wave form Generation Component
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module WaveformGen
          (clk,
           reset,
           enb,
           phaseIdx,
           sine);


  input   clk;
  input   reset;
  input   enb;
  input   [12:0] phaseIdx;  // ufix13_E7
  output  signed [15:0] sine;  // sfix16_En14


  reg [12:0] phaseIdxReg;  // ufix13_E7
  wire selsign;  // ufix1
  reg  [2:0] SelsignRegister_reg;  // ufix1 [3]
  wire selsignreg;  // ufix1
  wire [11:0] lutaddrexd;  // ufix12
  wire addrOverFsin;  // ufix1
  reg  [2:0] AddrOverFsinRegister_reg;  // ufix1 [3]
  wire addrOverFsinreg;  // ufix1
  wire seladdr;  // ufix1
  wire [10:0] lutaddr1;  // ufix11
  wire [11:0] lutaddrmax;  // ufix12
  wire [12:0] subtractor_sub_temp;  // ufix13
  wire [12:0] subtractor_1;  // ufix13
  wire [12:0] subtractor_2;  // ufix13
  wire [10:0] lutaddr2;  // ufix11
  wire [10:0] lutaddrsin;  // ufix11
  wire signed [15:0] lutoutsin;  // sfix16_En14
  wire signed [15:0] ampOne;  // sfix16_En14
  wire signed [15:0] lutoutsin_ampOne;  // sfix16_En14
  wire signed [16:0] uminus_cast;  // sfix17_En14
  wire signed [16:0] uminus_cast_1;  // sfix17_En14
  wire signed [15:0] lutoutsin_ampOne_inv;  // sfix16_En14


  always @(posedge clk or posedge reset)
    begin : phaseIdxRegister_process
      if (reset == 1'b1) begin
        phaseIdxReg <= 13'b0000000000000;
      end
      else begin
        if (enb) begin
          phaseIdxReg <= phaseIdx;
        end
      end
    end



  // Sine sign selection signal
  assign selsign = phaseIdxReg[12];



  always @(posedge clk or posedge reset)
    begin : SelsignRegister_process
      if (reset == 1'b1) begin
        SelsignRegister_reg <= {3{1'b0}};
      end
      else begin
        if (enb) begin
          SelsignRegister_reg[0] <= selsign;
          SelsignRegister_reg[32'sd2:32'sd1] <= SelsignRegister_reg[32'sd1:32'sd0];
        end
      end
    end

  assign selsignreg = SelsignRegister_reg[2];



  // Get extended LUT address for overflow handling
  assign lutaddrexd = phaseIdxReg[11:0];



  // Detect sine overflow
  assign addrOverFsin = lutaddrexd == 12'b100000000000;



  always @(posedge clk or posedge reset)
    begin : AddrOverFsinRegister_process
      if (reset == 1'b1) begin
        AddrOverFsinRegister_reg <= {3{1'b0}};
      end
      else begin
        if (enb) begin
          AddrOverFsinRegister_reg[0] <= addrOverFsin;
          AddrOverFsinRegister_reg[32'sd2:32'sd1] <= AddrOverFsinRegister_reg[32'sd1:32'sd0];
        end
      end
    end

  assign addrOverFsinreg = AddrOverFsinRegister_reg[2];



  assign seladdr = phaseIdxReg[11];



  assign lutaddr1 = phaseIdxReg[10:0];



  // Map LUT address in correct phase
  assign lutaddrmax = 12'b100000000000;



  assign subtractor_1 = {1'b0, lutaddrmax};
  assign subtractor_2 = {2'b0, lutaddr1};
  assign subtractor_sub_temp = subtractor_1 - subtractor_2;
  assign lutaddr2 = subtractor_sub_temp[10:0];



  assign lutaddrsin = (seladdr == 1'b0 ? lutaddr1 :
              lutaddr2);



  LookUpTableGen u_SineWave_inst (.clk(clk),
                                  .reset(reset),
                                  .enb(enb),
                                  .lutaddr(lutaddrsin),  // ufix11
                                  .lutoutput(lutoutsin)  // sfix16_En14
                                  );

  assign ampOne = 16'sb0100000000000000;



  // Assign sine amplitude One
  assign lutoutsin_ampOne = (addrOverFsinreg == 1'b0 ? lutoutsin :
              ampOne);



  assign uminus_cast = {lutoutsin_ampOne[15], lutoutsin_ampOne};
  assign uminus_cast_1 =  - (uminus_cast);
  assign lutoutsin_ampOne_inv = uminus_cast_1[15:0];



  // Select sign of Sine output
  assign sine = (selsignreg == 1'b0 ? lutoutsin_ampOne :
              lutoutsin_ampOne_inv);



endmodule  // WaveformGen

