# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/topCons.xdc

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_alphaScramble_0_0/top_alphaScramble_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_alphaScramble_0_0 || ORIG_REF_NAME==top_alphaScramble_0_0} -quiet] -quiet

# IP: bd/top/ip/top_RS_0_0/top_RS_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_RS_0_0 || ORIG_REF_NAME==top_RS_0_0} -quiet] -quiet

# IP: bd/top/ip/top_sigSource_0_0/top_sigSource_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_sigSource_0_0 || ORIG_REF_NAME==top_sigSource_0_0} -quiet] -quiet

# IP: bd/top/ip/top_Con_Interleaver_0_0/top_Con_Interleaver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_Con_Interleaver_0_0 || ORIG_REF_NAME==top_Con_Interleaver_0_0} -quiet] -quiet

# IP: bd/top/ip/top_dec2bin_0_0/top_dec2bin_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dec2bin_0_0 || ORIG_REF_NAME==top_dec2bin_0_0} -quiet] -quiet

# IP: bd/top/ip/top_Con_Encoder_0_0/top_Con_Encoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_Con_Encoder_0_0 || ORIG_REF_NAME==top_Con_Encoder_0_0} -quiet] -quiet

# IP: bd/top/ip/top_PolarityShift_0_0/top_PolarityShift_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_PolarityShift_0_0 || ORIG_REF_NAME==top_PolarityShift_0_0} -quiet] -quiet

# IP: bd/top/ip/top_PolarityShift_1_0/top_PolarityShift_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_PolarityShift_1_0 || ORIG_REF_NAME==top_PolarityShift_1_0} -quiet] -quiet

# IP: bd/top/ip/top_dds_compiler_0_0/top_dds_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dds_compiler_0_0 || ORIG_REF_NAME==top_dds_compiler_0_0} -quiet] -quiet

# IP: bd/top/ip/top_dds_compiler_0_1/top_dds_compiler_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dds_compiler_0_1 || ORIG_REF_NAME==top_dds_compiler_0_1} -quiet] -quiet

# IP: bd/top/ip/top_mult_gen_0_0/top_mult_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_mult_gen_0_0 || ORIG_REF_NAME==top_mult_gen_0_0} -quiet] -quiet

# IP: bd/top/ip/top_c_addsub_0_0/top_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_c_addsub_0_0 || ORIG_REF_NAME==top_c_addsub_0_0} -quiet] -quiet

# IP: bd/top/ip/top_EN_Gen_0_0/top_EN_Gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_EN_Gen_0_0 || ORIG_REF_NAME==top_EN_Gen_0_0} -quiet] -quiet

# IP: bd/top/ip/top_fir_compiler_0_0/top_fir_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_fir_compiler_0_0 || ORIG_REF_NAME==top_fir_compiler_0_0} -quiet] -quiet

# IP: bd/top/ip/top_fir_compiler_0_1/top_fir_compiler_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_fir_compiler_0_1 || ORIG_REF_NAME==top_fir_compiler_0_1} -quiet] -quiet

# IP: bd/top/ip/top_mult_gen_0_3/top_mult_gen_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_mult_gen_0_3 || ORIG_REF_NAME==top_mult_gen_0_3} -quiet] -quiet

# IP: bd/top/ip/top_terminal_0_0/top_terminal_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_terminal_0_0 || ORIG_REF_NAME==top_terminal_0_0} -quiet] -quiet

# IP: bd/top/ip/top_ila_0_0/top_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ila_0_0 || ORIG_REF_NAME==top_ila_0_0} -quiet] -quiet

# XDC: f:/Git_Repository/DVB-S/Vivado_BU01/Vivado2.gen/sources_1/bd/top/top_ooc.xdc
