set_property IOSTANDARD LVCMOS33 [get_ports clk_0]
set_property PACKAGE_PIN U18 [get_ports clk_0]
set_property PACKAGE_PIN N15 [get_ports reset_n_0]
set_property IOSTANDARD LVCMOS33 [get_ports reset_n_0]
set_property IOSTANDARD LVCMOS33 [get_ports {alphaScramble_OUT_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {alphaScramble_OUT_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {alphaScramble_OUT_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {alphaScramble_OUT_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {alphaScramble_OUT_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {alphaScramble_OUT_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {alphaScramble_OUT_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {alphaScramble_OUT_0[0]}]
set_property PACKAGE_PIN W19 [get_ports {alphaScramble_OUT_0[7]}]
set_property PACKAGE_PIN W18 [get_ports {alphaScramble_OUT_0[6]}]
set_property PACKAGE_PIN R14 [get_ports {alphaScramble_OUT_0[5]}]
set_property PACKAGE_PIN P14 [get_ports {alphaScramble_OUT_0[4]}]
set_property PACKAGE_PIN Y17 [get_ports {alphaScramble_OUT_0[3]}]
set_property PACKAGE_PIN Y16 [get_ports {alphaScramble_OUT_0[2]}]
set_property PACKAGE_PIN W15 [get_ports {alphaScramble_OUT_0[1]}]
set_property PACKAGE_PIN V15 [get_ports {alphaScramble_OUT_0[0]}]

create_clock -period 10.000 -name clk_0 -waveform {0.000 5.000} [get_ports clk_0]

set_property IOSTANDARD LVCMOS33 [get_ports ce_out_0]
set_property PACKAGE_PIN W13 [get_ports ce_out_0]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_0_IBUF_BUFG]
